#!/bin/bash
# The uninstall script for my vim dotfiles.

########################################################################
## Configs #############################################################
########################################################################
BUNDLE_DIR="/bundle"
SOURCE_DIR="/available-bundles"
REL_PATH="${PWD##*$SOURCE_DIR}"
NAME="enablebundle"

########################################################################
## Verify input ########################################################
########################################################################
if [ -z "$1" ]; then
	echo "[X] ERROR -- No bundle supplied."
	exit 1
fi

BUNDLE="$1"
	
########################################################################
## Disable bundle #######################################################
########################################################################
if [ "$NAME" == "`basename $0`" ]; then
	if [ ! -d "$SOURCE_DIR/$BUNDLE" ]; then
		echo "[X] ERROR -- Supplied name was not found as a valid bundle."
		exit 2
	fi
	
	if [ ! -d "$BUNDLE_DIR/$BUNDLE" ]; then
		echo "[X] ERROR -- Bundle is already disabled."
		exit 3
	fi
	
	echo "Disabling $BUNDLE bundle..."
    rm "$BUNDLE_DIR/$BUNDLE"
    
    echo "$BUNDLE disabled."
fi    
done
